package main

import (
	"github.com/gin-gonic/gin"
	"github.com/siskinc/srv-name-list/global"
	_ "github.com/siskinc/srv-name-list/global"
	"github.com/siskinc/srv-name-list/routes"
	

	_ "github.com/siskinc/srv-name-list/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description 名单管理系统
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8000
// @BasePath /name-list
func main() {
	router := gin.Default()
	routes.Init(router)
	router.Run(global.Config.ServerAddress())
}
