basePath: /name-list
definitions:
  httpx.JSONResult:
    properties:
      code:
        description: 回包code，表明是否正确，在code == 0时，表明服务正常
        type: integer
      data:
        description: 数据
        type: object
      message:
        description: 回报message，在code != 0时，展示给前端
        example: success
        type: string
    type: object
  httpx.JSONResultPaged:
    properties:
      code:
        description: 回包code，表明是否正确，在code == 0时，表明服务正常
        type: integer
      data:
        description: 数据
        type: object
      message:
        description: 回报message，在code != 0时，展示给前端
        example: success
        type: string
      total:
        description: 总数量
        type: integer
    type: object
  list_item.CreateListItemInfo:
    properties:
      code:
        type: string
      extra:
        additionalProperties: true
        type: object
      is_valid:
        type: boolean
      namespace:
        type: string
      values:
        description: 与list type中的fields一一对应的
        items:
          type: string
        type: array
    required:
    - code
    - is_valid
    - namespace
    - values
    type: object
  list_item.ItemHitAllReq:
    properties:
      code_list:
        description: 名单类型code, 如果不传, 或者传入的长度为0, 默认命中所有code
        items:
          type: string
        type: array
      data:
        description: 数据
        type: string
      namespace:
        description: 命名空间
        type: string
    required:
    - data
    - namespace
    type: object
  list_item.ItemHitAllResp:
    properties:
      hit_list_item_list:
        items:
          $ref: '#/definitions/models.ListItem'
        type: array
    type: object
  list_item.ItemHitPreReq:
    properties:
      data:
        description: 数据
        type: string
      list_item_id:
        description: 名单项ID
        type: string
    required:
    - data
    - list_item_id
    type: object
  list_item.ItemHitPreResp:
    properties:
      hit:
        type: boolean
      list_item:
        $ref: '#/definitions/models.ListItem'
      resource:
        type: string
    type: object
  list_item.UpdateListItemInfo:
    properties:
      extra:
        additionalProperties: true
        description: 可自定义的结构, 不管控
        type: object
      is_valid:
        description: 是否生效
        type: boolean
    type: object
  list_type.CreateListTypeReq:
    properties:
      code:
        description: 名单类型编码
        example: telephone
        type: string
      description:
        description: 描述
        example: description
        type: string
      fields:
        description: 这类名单的值被构建的字段
        example:
        - telephone
        - id_card
        items:
          type: string
        type: array
      is_valid:
        description: 是否生效
        type: boolean
      namespace:
        description: 命名空间
        example: anti-fraud
        type: string
    type: object
  list_type.UpdateListTypeReq:
    properties:
      description:
        description: 描述
        example: description
        type: string
      is_valid:
        description: 是否生效
        type: boolean
    required:
    - description
    - is_valid
    type: object
  models.ListItem:
    properties:
      code:
        description: 名单类型编码
        example: telephone__red
        type: string
      extra:
        additionalProperties: true
        description: 可自定义的结构, 不管控
        type: object
      id:
        description: 主键id
        example: 60d2b17f70d9d2f0db53f866
        type: string
      is_valid:
        description: 是否生效
        type: boolean
      multi_value:
        description: 多项值列表，如果名单是由多个字段构成的，可一一罗列出每个字段的值，如：[{"key":"field1","value":"value1"},{"key":"field2","value":"value2"}]
        items:
          $ref: '#/definitions/models.MultiValueItem'
        type: array
      namespace:
        description: 命名空间
        example: anti-fraud
        type: string
      value:
        description: 名单项的值
        example: "13333333333"
        type: string
    type: object
  models.ListType:
    properties:
      code:
        description: 名单类型编码
        example: telephone__red
        type: string
      description:
        description: 描述
        example: descriptions
        type: string
      fields:
        description: 这类名单的值被构建的字段
        example:
        - telephone
        - id_card
        items:
          type: string
        type: array
      id:
        description: 主键id
        example: 60d2b17f70d9d2f0db53f866
        type: string
      is_valid:
        description: 是否生效
        type: boolean
      namespace:
        description: 命名空间
        example: anti-fraud
        type: string
    type: object
  models.MultiValueItem:
    properties:
      key:
        description: field name
        example: telephone
        type: string
      value:
        description: value
        example: "13333333333"
        type: string
    type: object
  models.Namespace:
    properties:
      code:
        description: 命名空间code
        example: anti-fraud
        type: string
      description:
        description: 描述
        example: anti fraud use
        type: string
      id:
        description: 主键id
        example: 60d2b17f70d9d2f0db53f866
        type: string
    type: object
  namespace.CreateNamespaceReq:
    properties:
      code:
        description: 命名空间code
        example: anti-fraud
        type: string
      description:
        description: 描述
        example: anti fraud use
        type: string
    required:
    - code
    - description
    type: object
  namespace.UpdateNamespaceReq:
    properties:
      description:
        description: 描述
        type: string
    required:
    - description
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 名单管理系统
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /item:
    get:
      consumes:
      - application/json
      description: 名单项查找功能, 通过code, is_valid, 分页
      parameters:
      - description: Code
        in: query
        name: code
        type: string
      - description: 是否生效
        in: query
        name: isValid
        type: boolean
      - description: 命名空间
        in: query
        name: namespace
        required: true
        type: string
      - description: PageIndex
        in: query
        name: pageIndex
        type: integer
      - description: PageSize
        in: query
        name: pageSize
        type: integer
      - description: SortedField
        in: query
        name: sortedField
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复查询成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResultPaged'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.ListItem'
                  type: array
              type: object
      summary: 名单项查找功能
      tags:
      - 名单项
    post:
      consumes:
      - application/json
      description: 名单项创建功能
      parameters:
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_item.CreateListItemInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复创建成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListItem'
              type: object
      summary: 名单项创建功能
      tags:
      - 名单项
  /item-hit/all:
    post:
      consumes:
      - application/json
      description: 名单项命中, 返回命中的所有名单项
      parameters:
      - description: 预命中信息
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_item.ItemHitAllReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/list_item.ItemHitAllResp'
              type: object
      summary: 名单项命中
      tags:
      - 名单项命中
  /item-hit/pre:
    post:
      consumes:
      - application/json
      description: 名单项预命中, 指定某个名单项, 能够判断数据是否能够命中该名单项, 如果不能, 输出不能命中的原因
      parameters:
      - description: 命中信息
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_item.ItemHitPreReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复创建成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/list_item.ItemHitPreResp'
              type: object
      summary: 名单项预命中
      tags:
      - 名单项命中
  /item/{id}:
    delete:
      consumes:
      - application/json
      description: 名单项删除功能, 通过list_item_id删除
      parameters:
      - description: 名单项id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.JSONResult'
      summary: 名单项删除功能
      tags:
      - 名单项
    patch:
      consumes:
      - application/json
      description: 名单项修改功能, 通过code, is_valid, 分页
      parameters:
      - description: 名单项id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_item.UpdateListItemInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复更新成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListItem'
              type: object
      summary: 名单项修改功能
      tags:
      - 名单项
  /namespace:
    get:
      consumes:
      - application/json
      description: 命名空间查找功能
      parameters:
      - description: Code 命名空间code
        in: query
        name: code
        type: string
      - description: PageIndex 页码
        in: query
        name: pageIndex
        type: integer
      - description: PageSize 分页数量
        in: query
        name: pageSize
        type: integer
      - description: SortedField 排序字段
        in: query
        name: sortedField
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复查询成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResultPaged'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Namespace'
                  type: array
              type: object
      summary: 命名空间查找功能
      tags:
      - 命名空间
    post:
      consumes:
      - application/json
      description: 命名空间创建功能
      parameters:
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/namespace.CreateNamespaceReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复创建成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.Namespace'
              type: object
      summary: 命名空间创建功能
      tags:
      - 命名空间
  /namespace/{id}:
    delete:
      consumes:
      - application/json
      description: 命名空间删除功能, 通过namespace_id删除
      parameters:
      - description: 命名空间id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.JSONResult'
      summary: 命名空间删除功能
      tags:
      - 命名空间
    patch:
      consumes:
      - application/json
      description: 命名空间修改功能
      parameters:
      - description: 命名空间id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/namespace.UpdateNamespaceReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复更新成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.Namespace'
              type: object
      summary: 命名空间修改功能
      tags:
      - 命名空间
  /type:
    get:
      consumes:
      - application/json
      description: 名单类型查找功能, 通过code, is_valid, 分页
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: isValid
        type: boolean
      - in: query
        name: namespace
        type: string
      - in: query
        name: pageIndex
        type: integer
      - in: query
        name: pageSize
        type: integer
      - in: query
        name: sortedField
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复查询成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResultPaged'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.ListType'
                  type: array
              type: object
      summary: 名单类型查找功能
      tags:
      - 名单类型
    post:
      consumes:
      - application/json
      description: 名单类型创建功能
      parameters:
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_type.CreateListTypeReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复创建成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListType'
              type: object
      summary: 名单类型创建功能
      tags:
      - 名单类型
  /type/{id}:
    delete:
      consumes:
      - application/json
      description: 名单类型删除功能, 通过list_type_id删除
      parameters:
      - description: 名单类型id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复删除成功的名单类型数据
          schema:
            $ref: '#/definitions/httpx.JSONResult'
      summary: 名单类型删除功能
      tags:
      - 名单类型
    patch:
      consumes:
      - application/json
      description: 名单类型修改功能
      parameters:
      - description: 名单类型id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_type.UpdateListTypeReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复更新成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListType'
              type: object
      summary: 名单类型修改功能
      tags:
      - 名单类型
swagger: "2.0"
