basePath: /name-list
definitions:
  httpx.JSONResult:
    properties:
      code:
        description: 回包code，表明是否正确，在code == 0时，表明服务正常
        type: integer
      data:
        description: 数据
        type: object
      message:
        description: 回报message，在code != 0时，展示给前端
        type: string
    type: object
  httpx.JSONResultPaged:
    properties:
      code:
        description: 回包code，表明是否正确，在code == 0时，表明服务正常
        type: integer
      data:
        description: 数据
        type: object
      message:
        description: 回报message，在code != 0时，展示给前端
        type: string
      total:
        description: 总数量
        type: integer
    type: object
  list_item.ListItemCreateInfo:
    properties:
      code:
        type: string
      extra:
        additionalProperties: true
        type: object
      is_valid:
        type: boolean
      namespace:
        type: string
      values:
        description: 与list type中的fields一一对应的
        items:
          type: string
        type: array
    required:
    - code
    - is_valid
    - namespace
    - values
    type: object
  list_item.ListItemUpdateInfo:
    properties:
      extra:
        additionalProperties: true
        description: 可自定义的结构, 不管控
        type: object
      is_valid:
        description: 是否生效
        type: boolean
    type: object
  list_type.CreateListTypeReq:
    properties:
      code:
        description: 名单类型编码
        type: string
      description:
        description: 描述
        type: string
      fields:
        description: 这类名单的值被构建的字段
        items:
          type: string
        type: array
      is_valid:
        description: 是否生效
        type: boolean
      namespace:
        description: 命名空间
        type: string
    type: object
  list_type.UpdateListTypeReq:
    properties:
      description:
        description: 描述
        type: string
      is_valid:
        description: 是否生效
        type: boolean
    type: object
  models.ListItem:
    properties:
      code:
        description: 名单类型编码
        type: string
      extra:
        additionalProperties: true
        description: 可自定义的结构, 不管控
        type: object
      id:
        description: 主键id
        type: string
      is_valid:
        description: 是否生效
        type: boolean
      multi_value:
        description: 多项值列表，如果名单是由多个字段构成的，可一一罗列出每个字段的值，如：[{"key":"field1","value":"value1"},{"key":"field2","value":"value2"}]
        items:
          $ref: '#/definitions/models.MultiValueItem'
        type: array
      namespace:
        description: 命名空间
        type: string
      value:
        description: 名单项的值
        type: string
    type: object
  models.ListType:
    properties:
      code:
        description: 名单类型编码
        type: string
      description:
        description: 描述
        type: string
      fields:
        description: 这类名单的值被构建的字段
        items:
          type: string
        type: array
      id:
        description: 主键id
        type: string
      is_valid:
        description: 是否生效
        type: boolean
      namespace:
        description: 命名空间
        type: string
    type: object
  models.MultiValueItem:
    properties:
      key:
        description: field name
        type: string
      value:
        description: value
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /item:
    get:
      consumes:
      - application/json
      description: 名单项查找功能, 通过code, is_valid, 分页
      parameters:
      - description: 是否生效
        in: query
        name: is_valid
        type: boolean
      - description: 名单类型编码
        in: query
        minLength: 1
        name: code
        type: string
      - default: 1
        description: 页码
        in: query
        minimum: 1
        name: page_index
        type: integer
      - default: 10
        description: 分页大小
        in: query
        minimum: 10
        name: page_size
        type: integer
      - description: 排序方式
        in: query
        minLength: 1
        name: sorted_field
        type: string
      - description: 命名空间
        in: query
        minLength: 1
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复查询成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResultPaged'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.ListItem'
                  type: array
              type: object
      summary: 名单项查找功能
      tags:
      - 名单项
    post:
      consumes:
      - application/json
      description: 名单项创建功能
      parameters:
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_item.ListItemCreateInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复创建成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListItem'
              type: object
      summary: 名单项创建功能
      tags:
      - 名单项
  /item/{id}:
    delete:
      consumes:
      - application/json
      description: 名单项删除功能, 通过list_item_id删除
      parameters:
      - description: 名单项id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.JSONResult'
      summary: 名单项删除功能
      tags:
      - 名单项
    patch:
      consumes:
      - application/json
      description: 名单项修改功能, 通过code, is_valid, 分页
      parameters:
      - description: 名单项id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_item.ListItemUpdateInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复更新成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListItem'
              type: object
      summary: 名单项修改功能
      tags:
      - 名单项
  /type:
    get:
      consumes:
      - application/json
      description: 名单类型查找功能, 通过code, is_valid, 分页
      parameters:
      - description: 是否生效
        in: query
        name: is_valid
        type: boolean
      - description: 名单类型编码
        in: query
        minLength: 1
        name: code
        type: string
      - default: 1
        description: 页码
        in: query
        minimum: 1
        name: page_index
        type: integer
      - default: 10
        description: 分页大小
        in: query
        minimum: 10
        name: page_size
        type: integer
      - description: 排序方式
        in: query
        minLength: 1
        name: sorted_field
        type: string
      - description: 命名空间
        in: query
        minLength: 1
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复查询成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResultPaged'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.ListType'
                  type: array
              type: object
      summary: 名单类型查找功能
      tags:
      - 名单类型
    post:
      consumes:
      - application/json
      description: 名单类型创建功能
      parameters:
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_type.CreateListTypeReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复创建成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListType'
              type: object
      summary: 名单类型创建功能
      tags:
      - 名单类型
  /type/{id}:
    delete:
      consumes:
      - application/json
      description: 名单类型删除功能, 通过list_type_id删除
      parameters:
      - description: 名单类型id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复删除成功的名单类型数据
          schema:
            $ref: '#/definitions/httpx.JSONResult'
      summary: 名单类型删除功能
      tags:
      - 名单类型
    patch:
      consumes:
      - application/json
      description: 名单类型修改功能, 通过code, is_valid, 分页
      parameters:
      - description: 名单类型id
        in: path
        minLength: 1
        name: id
        required: true
        type: string
      - description: 名单属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/list_type.UpdateListTypeReq'
      produces:
      - application/json
      responses:
        "200":
          description: 正常回包, 回复更新成功的名单类型数据
          schema:
            allOf:
            - $ref: '#/definitions/httpx.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.ListType'
              type: object
      summary: 名单类型修改功能
      tags:
      - 名单类型
swagger: "2.0"
